// Generated by CoffeeScript 1.8.0
(function() {
  var portName, serialport, sp;

  serialport = require('serialport');

  portName = '/dev/ttyACM0';

  sp = new serialport.SerialPort(portName, {
    baudRate: 9600,
    dataBits: 8,
    parity: 'none',
    stopBits: 1,
    flowControl: false,
    parser: serialport.parsers.readline("\n")
  });

  sp.on('data', function(input) {
    return console.log("部屋の温度は、" + input);
  });

}).call(this);

//# sourceMappingURL=serialport_test.js.map
