// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(robot) {
    robot.hear(/badger/i, function(msg) {
      return msg.reply("Badgers? BADGERS? WE DON'T NEED NO STINKIN BADGERS");
    });
    return robot.hear(/I like pie/i, function(msg) {
      return msg.reply("makes a freshly baked pie");
    });
  };

}).call(this);

//# sourceMappingURL=example.js.map
